import { MigrationInterface, QueryRunner } from "typeorm";

export class MyNewMigration1767284258965 implements MigrationInterface {
    name = 'MyNewMigration1767284258965'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_session_reviews_menteeId\` ON \`session_reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_session_reviews_mentorId\` ON \`session_reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_session_reviews_sessionId\` ON \`session_reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_group_session_participants_groupSessionId\` ON \`group_session_participants\``);
        await queryRunner.query(`DROP INDEX \`IDX_group_session_participants_menteeId\` ON \`group_session_participants\``);
        await queryRunner.query(`DROP INDEX \`IDX_group_session_participants_unique\` ON \`group_session_participants\``);
        await queryRunner.query(`DROP INDEX \`IDX_group_sessions_mentorId\` ON \`group_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_group_sessions_scheduledAt\` ON \`group_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_mentorship_requests_mentee\` ON \`mentorship_requests\``);
        await queryRunner.query(`DROP INDEX \`IDX_mentorship_requests_mentor\` ON \`mentorship_requests\``);
        await queryRunner.query(`DROP INDEX \`IDX_mentorship_requests_mentor_mentee_unique\` ON \`mentorship_requests\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` DROP COLUMN \`timezone\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` ADD \`timezone\` varchar(255) NOT NULL DEFAULT 'UTC'`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP FOREIGN KEY \`FK_c63848de9a345d16698e56aa809\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP FOREIGN KEY \`FK_da84943e34461834ce82b0b5c19\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP FOREIGN KEY \`FK_b8a51c2490a5c8ca2e14c0c87e6\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP COLUMN \`sessionId\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD \`sessionId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD UNIQUE INDEX \`IDX_c63848de9a345d16698e56aa80\` (\`sessionId\`)`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP COLUMN \`groupSessionId\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD \`groupSessionId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP COLUMN \`menteeId\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD \`menteeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP COLUMN \`mentorId\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD \`mentorId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` CHANGE \`mentorViewed\` \`mentorViewed\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` DROP COLUMN \`groupSessionId\``);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` ADD \`groupSessionId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` DROP COLUMN \`menteeId\``);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` ADD \`menteeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` CHANGE \`hasSubmittedReview\` \`hasSubmittedReview\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`group_sessions\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`group_sessions\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`group_sessions\` DROP COLUMN \`mentorId\``);
        await queryRunner.query(`ALTER TABLE \`group_sessions\` ADD \`mentorId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`mentorship_requests\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`mentorship_requests\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_fc0de1dcd2d1c3e2cfea0d218e\` ON \`session_reviews\` (\`groupSessionId\`, \`menteeId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_b07f136b9ee3e2d2cf244f57fd\` ON \`session_reviews\` (\`sessionId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7025410440722b39e0786a933c\` ON \`group_session_participants\` (\`groupSessionId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1ce8f424d276ed240a85a01314\` ON \`group_session_participants\` (\`menteeId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_205a627720b69fa9e7c72d562a\` ON \`group_session_participants\` (\`groupSessionId\`, \`menteeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a628f87af4b2960eddbc4b8300\` ON \`group_sessions\` (\`mentorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_28e99ca3d559af24c34edabacd\` ON \`group_sessions\` (\`scheduledAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_645ece76825e10b235a0803430\` ON \`mentorship_requests\` (\`mentorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ea1cdd0146653d13408eb9377b\` ON \`mentorship_requests\` (\`menteeId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_b1ac83669a9df7dc712950d804\` ON \`mentorship_requests\` (\`mentorId\`, \`menteeId\`)`);
        await queryRunner.query(`ALTER TABLE \`app_notifications\` ADD CONSTRAINT \`FK_905763ebe581ee8c69455b46295\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD CONSTRAINT \`FK_c63848de9a345d16698e56aa809\` FOREIGN KEY (\`sessionId\`) REFERENCES \`sessions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD CONSTRAINT \`FK_016e4d5e94a30e08c0e65bfedba\` FOREIGN KEY (\`groupSessionId\`) REFERENCES \`group_sessions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD CONSTRAINT \`FK_da84943e34461834ce82b0b5c19\` FOREIGN KEY (\`menteeId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD CONSTRAINT \`FK_b8a51c2490a5c8ca2e14c0c87e6\` FOREIGN KEY (\`mentorId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` ADD CONSTRAINT \`FK_7025410440722b39e0786a933ca\` FOREIGN KEY (\`groupSessionId\`) REFERENCES \`group_sessions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` ADD CONSTRAINT \`FK_1ce8f424d276ed240a85a013143\` FOREIGN KEY (\`menteeId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`group_sessions\` ADD CONSTRAINT \`FK_a628f87af4b2960eddbc4b8300e\` FOREIGN KEY (\`mentorId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mentorship_requests\` ADD CONSTRAINT \`FK_645ece76825e10b235a0803430e\` FOREIGN KEY (\`mentorId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mentorship_requests\` ADD CONSTRAINT \`FK_ea1cdd0146653d13408eb9377be\` FOREIGN KEY (\`menteeId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`mentorship_requests\` DROP FOREIGN KEY \`FK_ea1cdd0146653d13408eb9377be\``);
        await queryRunner.query(`ALTER TABLE \`mentorship_requests\` DROP FOREIGN KEY \`FK_645ece76825e10b235a0803430e\``);
        await queryRunner.query(`ALTER TABLE \`group_sessions\` DROP FOREIGN KEY \`FK_a628f87af4b2960eddbc4b8300e\``);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` DROP FOREIGN KEY \`FK_1ce8f424d276ed240a85a013143\``);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` DROP FOREIGN KEY \`FK_7025410440722b39e0786a933ca\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP FOREIGN KEY \`FK_b8a51c2490a5c8ca2e14c0c87e6\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP FOREIGN KEY \`FK_da84943e34461834ce82b0b5c19\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP FOREIGN KEY \`FK_016e4d5e94a30e08c0e65bfedba\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP FOREIGN KEY \`FK_c63848de9a345d16698e56aa809\``);
        await queryRunner.query(`ALTER TABLE \`app_notifications\` DROP FOREIGN KEY \`FK_905763ebe581ee8c69455b46295\``);
        await queryRunner.query(`DROP INDEX \`IDX_b1ac83669a9df7dc712950d804\` ON \`mentorship_requests\``);
        await queryRunner.query(`DROP INDEX \`IDX_ea1cdd0146653d13408eb9377b\` ON \`mentorship_requests\``);
        await queryRunner.query(`DROP INDEX \`IDX_645ece76825e10b235a0803430\` ON \`mentorship_requests\``);
        await queryRunner.query(`DROP INDEX \`IDX_28e99ca3d559af24c34edabacd\` ON \`group_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_a628f87af4b2960eddbc4b8300\` ON \`group_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_205a627720b69fa9e7c72d562a\` ON \`group_session_participants\``);
        await queryRunner.query(`DROP INDEX \`IDX_1ce8f424d276ed240a85a01314\` ON \`group_session_participants\``);
        await queryRunner.query(`DROP INDEX \`IDX_7025410440722b39e0786a933c\` ON \`group_session_participants\``);
        await queryRunner.query(`DROP INDEX \`IDX_b07f136b9ee3e2d2cf244f57fd\` ON \`session_reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_fc0de1dcd2d1c3e2cfea0d218e\` ON \`session_reviews\``);
        await queryRunner.query(`ALTER TABLE \`mentorship_requests\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`mentorship_requests\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`group_sessions\` DROP COLUMN \`mentorId\``);
        await queryRunner.query(`ALTER TABLE \`group_sessions\` ADD \`mentorId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`group_sessions\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`group_sessions\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` CHANGE \`hasSubmittedReview\` \`hasSubmittedReview\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` DROP COLUMN \`menteeId\``);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` ADD \`menteeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` DROP COLUMN \`groupSessionId\``);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` ADD \`groupSessionId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`group_session_participants\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` CHANGE \`mentorViewed\` \`mentorViewed\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP COLUMN \`mentorId\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD \`mentorId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP COLUMN \`menteeId\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD \`menteeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP COLUMN \`groupSessionId\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD \`groupSessionId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP INDEX \`IDX_c63848de9a345d16698e56aa80\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` DROP COLUMN \`sessionId\``);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD \`sessionId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD CONSTRAINT \`FK_b8a51c2490a5c8ca2e14c0c87e6\` FOREIGN KEY (\`mentorId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD CONSTRAINT \`FK_da84943e34461834ce82b0b5c19\` FOREIGN KEY (\`menteeId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`session_reviews\` ADD CONSTRAINT \`FK_c63848de9a345d16698e56aa809\` FOREIGN KEY (\`sessionId\`) REFERENCES \`sessions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sessions\` DROP COLUMN \`timezone\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` ADD \`timezone\` varchar(100) NOT NULL DEFAULT 'UTC'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_mentorship_requests_mentor_mentee_unique\` ON \`mentorship_requests\` (\`mentorId\`, \`menteeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_mentorship_requests_mentor\` ON \`mentorship_requests\` (\`mentorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_mentorship_requests_mentee\` ON \`mentorship_requests\` (\`menteeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_group_sessions_scheduledAt\` ON \`group_sessions\` (\`scheduledAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_group_sessions_mentorId\` ON \`group_sessions\` (\`mentorId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_group_session_participants_unique\` ON \`group_session_participants\` (\`groupSessionId\`, \`menteeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_group_session_participants_menteeId\` ON \`group_session_participants\` (\`menteeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_group_session_participants_groupSessionId\` ON \`group_session_participants\` (\`groupSessionId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_session_reviews_sessionId\` ON \`session_reviews\` (\`sessionId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_session_reviews_mentorId\` ON \`session_reviews\` (\`mentorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_session_reviews_menteeId\` ON \`session_reviews\` (\`menteeId\`)`);
    }

}
