import { DataSource } from 'typeorm';
import { Config } from '../common';
import {
  RefreshToken,
  AuditLog,
  PasswordReset,
  SystemConfig,
  UserNotification,
  AppNotification,
  User,
  MenteeProfile,
  MentorProfile,
  Session,
  SessionReview,
  MentorAvailability,
  GroupSession,
  GroupSessionParticipant,
  BibleBookmark,
  BibleHighlight,
  BibleReflection,
  BibleProgress,
  StudyProgress,
  StudySession,
  StudyReflection,
  Conversation,
  Message,
  ConversationParticipant,
} from '@/database/entities';

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: Config.database.host,
  port: Config.database.port,
  username: Config.database.username,
  password: Config.database.password,
  database: Config.database.name,
  synchronize: Config.database.synchronize,
  logging: false,
  ssl: Config.database.ssl,
  extra: {
    connectionLimit: 5,
    maxIdle: 5,
    idleTimeout: 10000,
  },
  entities: [
    RefreshToken,
    AuditLog,
    PasswordReset,
    SystemConfig,
    UserNotification,
    AppNotification,
    User,
    MenteeProfile,
    MentorProfile,
    Session,
    SessionReview,
    MentorAvailability,
    GroupSession,
    GroupSessionParticipant,
    BibleBookmark,
    BibleHighlight,
    BibleReflection,
    BibleProgress,
    StudyProgress,
    StudySession,
    StudyReflection,
    Conversation,
    Message,
    ConversationParticipant,
  ],
  migrations: ['src/database/migrations/*.ts'],
  subscribers: [],
});
